{% set name = "jupyterlab-blockly" %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jupyterlab_blockly-{{ version }}.tar.gz
  sha256: eb008cf49cd6ec9372dd6555a4dcc0ab69c86b6adcb219e9299351d6f2cc0c61

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - pip
    - python >=3.9
    - nodejs
    - hatchling >=1.5.0
    - hatch-nodejs-version >=0.3.2
    - hatch-jupyter-builder
    - jupyterlab >=4.0.0,<5
  run:
    - nodejs
    - python >=3.8
    - jupyterlab >=4.0.0,<5

test:
  imports:
    - jupyterlab_blockly
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/quantstack/jupyterlab-blockly
  summary: Blockly extension for JupyterLab.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - DenisaCG
    - hbcarlos
